### ISSUE TITLE
Connection errors are fatal

### ISSUE THREAD

**Issue by djeeg** [jaegertracing/jaeger-client-node#179]
Sometimes when deploying stacks in docker, the jaeger endpoint might not be available for the client.

This then seems to cause fatal errors, eg

```
Error: getaddrinfo ENOTFOUND jaeger
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

TypeError: Cannot read property 'spans' of undefined
    at UDPSender.flush (/serviceroot/node_modules/jaeger-client/src/reporters/udp_sender.js:114:32)
    at RemoteReporter.flush (/serviceroot/node_modules/jaeger-client/src/reporters/remote_reporter.js:65:53)
    at Timeout._onTimeout (/serviceroot/node_modules/jaeger-client/src/reporters/remote_reporter.js:47:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

Is there a way for the client to handle this gracefully?

As a temp workaround I test the port and disable

```
   const connectionTester = require('connection-tester');
   var output = connectionTester.test(
             host,
             port,
             500
    );
    var disable = settingfromconfig;
    if(output && output.error) {
        console.error("connectionTester failed - permanently disabling jaeger", output);
        disable = true;
    }

    var config = {
        disable: disable,
```

Is there a better way to do this?

**Comment by yurishkuro** [comment]
It appears as if the timer fires and calls flush() before the process was ever set. I can't say if it should be possible given the order of initialization, but seems exception itself is easy to prevent if you add the following to the udp_sender constructor

```
        this._batch = {
            'spans': []
        };
```

Would you be able to test if this would fix the issue?

**Comment by djeeg** [comment]
Looks like this has already been fixed https://github.com/jaegertracing/jaeger-client-node/pull/137
