### ISSUE TITLE
Remote reporter index out of range exception

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-node#181]
```
buffer.js:1182
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkInt (buffer.js:1182:11)
    at Buffer.writeUInt16BE (buffer.js:1249:5)
    at MessageRW.poolStrictWriteInto (/home/udocker/unpm/node_modules/thriftrw/message.js:165:12)
    at MessageRW.poolWriteInto (/home/udocker/unpm/node_modules/thriftrw/message.js:144:23)
    at MessageRW.writeInto (/home/udocker/unpm/node_modules/bufrw/base.js:83:10)
    at UDPSender.flush (/home/udocker/unpm/node_modules/jaeger-client/dist/src/reporters/udp_sender.js:147:84)
    at RemoteReporter.flush (/home/udocker/unpm/node_modules/jaeger-client/dist/src/reporters/remote_reporter.js:80:41)
    at Timeout._onTimeout (/home/udocker/unpm/node_modules/jaeger-client/dist/src/reporters/remote_reporter.js:58:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by black-adder** [comment]
This is on v2.7.0
