### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by aviranco** [jaegertracing/jaeger-client-node#210]
Hi,

I was getting the following error every time I started the application and crashed the application:
```
RangeError: Index out of range
    at checkInt (buffer.js:1182:11)
    at Buffer.writeUInt16BE (buffer.js:1249:5)
    at MessageRW.poolStrictWriteInto (/Users/aviranc/git/comet/node_modules/thriftrw/message.js:165:12)
    at MessageRW.poolWriteInto (/Users/aviranc/git/comet/node_modules/thriftrw/message.js:144:23)
    at MessageRW.writeInto (/Users/aviranc/git/comet/node_modules/bufrw/base.js:83:10)
    at UDPSender.flush (/Users/aviranc/git/comet/node_modules/jaeger-client/src/reporters/udp_sender.js:124:80)
    at RemoteReporter.flush (/Users/aviranc/git/comet/node_modules/jaeger-client/src/reporters/remote_reporter.js:57:53)
    at Timeout._onTimeout (/Users/aviranc/git/comet/node_modules/jaeger-client/src/reporters/remote_reporter.js:39:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Waiting for the debugger to disconnect...

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

```

After restarting the WebStorm IDE the error disappeared. 

Any idea what could cause such an error? I am not familiar with the internals of the jaeger-client, but due to the facts that:
1. I did testings for long time on the same WebStorm session trying to figure out about the Memory leak issue (#208)
2. It seems that the IDE restart made the problem solve, 

Is that possible that there is a shared state (probably shared memory?) between each application run that got corrupted? and any change it might be related to the memory leak issue?

Thanks,
Aviran

**Comment by black-adder** [comment]
Sorry, this was fixed in https://github.com/jaegertracing/jaeger-client-node/pull/195 but I never did a release, I'll do so today.

**Comment by aviranco** [comment]
@black-adder It might be possible that this fix also fixes a memory leak issue?

**Comment by black-adder** [comment]
possibly? can't say for sure, I'll look into the memory issues today

**Comment by aviranco** [comment]
@black-adder Thank you!
Looking forward for an update since I am trying to fix the memory leaks at the moment :)

**Comment by abraithwaite** [comment]
I'm running into this right now and can verify that `_process` is indeed set.  I don't see how they're related.

**Comment by yurishkuro** [comment]
@aviranco is this still an issue?

**Comment by aviranco** [comment]
@yurishkuro 
I could not re-created this issue, as soon as I've restarted the WebStorm IDE the issue was solved.
I can only guess it has something to do with shared state (but its only a guess)
