### ISSUE TITLE
Flaky test in RemoteSampler ?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#270]
https://travis-ci.org/jaegertracing/jaeger-client-node/jobs/396552174

```
204 passing (1s)
  3 failing
  1) RemoteSampler should set ratelimiting sampler:
     Uncaught TypeError: _this2._metrics.reporterSuccess.increment is not a function
      at dist/src/reporters/remote_reporter.js:105:43
      at UDPSender._invokeCallback (dist/src/reporters/udp_sender.js:116:9)
      at UDPSender.flush (dist/src/reporters/udp_sender.js:165:14)
      at RemoteReporter.flush (dist/src/reporters/remote_reporter.js:100:20)
      at Timeout._onTimeout (dist/src/reporters/remote_reporter.js:67:13)
  2) RemoteSampler should set per-operation sampler:
     Uncaught AssertionError: expected undefined to equal 1
      at RemoteControlledSampler.remoteSampler._onSamplerUpdate (dist/test/samplers/remote_sampler.js:186:20)
      at RemoteControlledSampler._parseSamplingServerResponse (dist/src/samplers/remote_sampler.js:154:14)
      at success (dist/src/samplers/remote_sampler.js:121:15)
      at IncomingMessage.<anonymous> (dist/src/util.js:196:11)
      at endReadableNT (_stream_readable.js:978:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
  3) RemoteSampler "after each" hook:
     Uncaught TypeError: _this2._metrics.reporterSuccess.increment is not a function
      at dist/src/reporters/remote_reporter.js:105:43
      at UDPSender._invokeCallback (dist/src/reporters/udp_sender.js:116:9)
      at UDPSender.flush (dist/src/reporters/udp_sender.js:165:14)
      at RemoteReporter.flush (dist/src/reporters/remote_reporter.js:100:20)
      at Timeout._onTimeout (dist/src/reporters/remote_reporter.js:67:13)
```

cc @black-adder

**Comment by yurishkuro** [comment]
Another failure, again in master build: https://travis-ci.org/jaegertracing/jaeger-client-node/jobs/396969052
