### ISSUE TITLE
reporter.name is not a function

### ISSUE THREAD

**Issue by FabianTe** [jaegertracing/jaeger-client-node#383]
## Requirement - what kind of business use case are you trying to solve?

I want to use the span logging, but I am unable to enable it. This is my config:

```js
const options = {
    tags: {
        serviceNameVersion: pkg.version
    },
    // metrics: metrics,
    logger: {
        info: (str) => log.info(`Jaeger-Tracer: ${str}`),
        error: (str) => log.error(`Jaeger-Tracer: ${str}`),
    },
    sampler: {
        type: 'const',
        param: 1
    },
    reporter: {
        logSpans: true,
        agentHost: '127.0.0.1', // FIXME: Use consul service
        agentPort: 6832
    }
};
```

## Problem - what in Jaeger blocks you from solving the requirement?

I can't enable the span logging. This is the error I am receiving:

```log
C:\NodeProject\cart-service\node_modules\jaeger-client\dist\src\configuration.js:336
            'Initializing Jaeger Tracer with ' + reporter.name() + ' and ' + sampler.name()
                                                          ^

TypeError: reporter.name is not a function
    at Object.initTracer (C:\NodeProject\cart-service\node_modules\jaeger-client\dist\src\configuration.js:336:59)
    at Object.createTracer (C:\NodeProject\lib\tracing.js:31:19)
    at Object.<anonymous> (C:\NodeProject\cart-service\js\main.js:9:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by yurishkuro** [comment]
I think it's already fixed in master

**Comment by FabianTe** [comment]
Maybe, but I just found my error too: The reporter should not be configured in the options, but rather the config property.
