### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by robross0606** [jaegertracing/jaeger-client-node#499]
Experiencing periodic "Converting circular structure to JSON" errors when finishing span tags.

**To Reproduce**
Unclear what is causing the issue, but it is always on the same stack trace:
```
Caused by TypeError: Converting circular structure to JSON
 --> starting at object with constructor 'LinkedListItem'
 | property 'before' -> object with constructor 'LinkedListItem'
 --- property 'behind' closes the circle
 at JSON.stringify (<anonymous>)
 at Function.getThriftTags (/usr/src/app/node_modules/jaeger-client/dist/src/thrift.js:84:23)
 at Function.getThriftLogs (/usr/src/app/node_modules/jaeger-client/dist/src/thrift.js:115:31)
 at Function.spanToThrift (/usr/src/app/node_modules/jaeger-client/dist/src/thrift.js:170:30)
 at RemoteReporter.report (/usr/src/app/node_modules/jaeger-client/dist/src/reporters/remote_reporter.js:85:41)
 at Tracer._report (/usr/src/app/node_modules/jaeger-client/dist/src/tracer.js:217:22)
 at Span.finish (/usr/src/app/node_modules/jaeger-client/dist/src/span.js:214:22)
```

**Expected behavior**
jaeger-client calls should use something like `fast-safe-stringify` to ensure they do not fail on self-referencing object structures.

**Version (please complete the following information):**
 - OS: Alpine Linux v3.11.11
 - Jaeger client version: 3.18.1
 - Deployment: Client deployed to K8S on Alpine v3.11.11 container.

**What troubleshooting steps did you try?**
Most of the troubleshooting steps seem to be focused on debugging communications between client and server.  This issue occurs client-side on the node.js application.

**Additional context**
Due to the nature of the problem, no further logging has been possible so we have not been able to determine a root cause of what circular structures are causing the issue.

**Comment by helloljq** [comment]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.getThriftTags (/Users/shiqi/repo/api-nest/node_modules/jaeger-client/src/thrift.js:61:21)
